# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonalManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  pod 'Then'
  pod 'ObjectMapper'
  pod 'CalendarKit'

  #View
  pod 'Material', '3.1.0'
  pod 'SnapKit', '4.2'
  pod 'PanModal'
  pod 'DGCharts'
  pod 'TinyConstraints'

end
